# This docker-compose.yml file is used to build and test quickly
# a specific version of Dolibarr
#
# Before build, define the variable DOLI_VERSION as following:
# $ export DOLI_VERSION=4.0.4
# And then, you can run :
# $ docker-compose up
#
# More information about Docker-compose : https://docs.docker.com/compose/

version: "3.8"

networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

secrets:
    mysql-user:
        file: ./secrets/mysql_user.secret
    mysql-password:
        file: ./secrets/mysql_password.secret

services:
    mariadb:
        # user: "${USER_ID}:${GROUP_ID}"
        image: mariadb:latest
        secrets:
            - mysql-user
            - mysql-password
        volumes:
            - ./volumes/mariadb:/var/lib/mysql:rw
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
            MYSQL_DATABASE: "dolibarr"
            MYSQL_USER_FILE: "/run/secrets/mysql-user"
            MYSQL_PASSWORD_FILE: "/run/secrets/mysql-password"
        networks:
            - internal-pod

    cron:
        # user: "${USER_ID}:${GROUP_ID}"
        build:
            context: ./images/${DOLI_IMAGE_TAG}
        image: ans/dolibarr:${DOLI_IMAGE_TAG}
        secrets:
            - mysql-user
            - mysql-password
        # volumes:
        #     - ./volumes/dolibarr/documents:/var/www/documents:rw
        #     - ./volumes/dolibarr/html:/var/www/html:rw
        #     - ./volumes/dolibarr/scripts:/var/www/scripts:rw
        #     - /etc/localtime:/etc/localtime:ro
        #     - /etc/timezone:/etc/timezone:ro
        environment:
            DOLI_CRON: 1
            DOLI_CRON_KEY: xxxx
            DOLI_CRON_USER: administrator
            DOLI_DB_USER_FILE: /run/secrets/mysql-user
            DOLI_DB_PASSWORD_FILE: /run/secrets/mysql-password
            DOLI_ADMIN_LOGIN: administrator
            DOLI_ADMIN_PASSWORD: admin456
            DOLI_DB_HOST: mariadb
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: http://localhost
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        networks:
            - internal-pod

    web:
        # user: "${USER_ID}:${GROUP_ID}"
        build:
            context: ./images/${DOLI_IMAGE_TAG}
        image: ans/dolibarr:${DOLI_IMAGE_TAG}
        secrets:
            - mysql-user
            - mysql-password
        # volumes:
        #     - ./volumes/dolibarr/documents:/var/www/documents:rw
        #     - ./volumes/dolibarr/html:/var/www/html:rw
        #     - ./volumes/dolibarr/scripts:/var/www/scripts:rw
        #     - /etc/localtime:/etc/localtime:ro
        #     - /etc/timezone:/etc/timezone:ro
        depends_on:
            - mariadb
        environment:
            DOLI_DB_USER_FILE: "/run/secrets/mysql-user"
            DOLI_DB_PASSWORD_FILE: "/run/secrets/mysql-password"
            DOLI_ADMIN_LOGIN: "administrator"
            DOLI_ADMIN_PASSWORD: "admin456"
            DOLI_DB_HOST: mariadb
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://localhost'
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        ports:
            - "80:80"
        networks:
            - internal-pod
            - external-pod
